var request = require("request");

var orders = {
  "orderLineDetailList": [
    {
      "id": 1,
      "userUsername": "admin_user",
      "orderDate": "2018-4-5",
      "totalAmount": "203.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-8",
      "measureDate": "2018-4-9",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 11,
      "userUsername": "admin_user",
      "orderDate": "2018-2-7",
      "totalAmount": "1079.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-1",
      "measureDate": "2018-4-14",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 21,
      "userUsername": "admin_user",
      "orderDate": "2018-4-13",
      "totalAmount": "429.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-3",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 31,
      "userUsername": "admin_user",
      "orderDate": "2018-4-24",
      "totalAmount": "732.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-1",
      "measureDate": "2018-4-7",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 41,
      "userUsername": "admin_user",
      "orderDate": "2018-3-11",
      "totalAmount": "1151.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-1",
      "measureDate": "2018-4-5",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 51,
      "userUsername": "admin_user",
      "orderDate": "2018-3-16",
      "totalAmount": "744.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-20",
      "measureDate": "2018-4-19",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 61,
      "userUsername": "admin_user",
      "orderDate": "2018-1-21",
      "totalAmount": "469.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-1",
      "measureDate": "2018-4-2",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 71,
      "userUsername": "admin_user",
      "orderDate": "2018-1-25",
      "totalAmount": "839.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-1",
      "measureDate": "2018-4-12",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 81,
      "userUsername": "admin_user",
      "orderDate": "2018-1-14",
      "totalAmount": "1051.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-18",
      "measureDate": "2018-4-13",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 91,
      "userUsername": "admin_user",
      "orderDate": "2018-3-12",
      "totalAmount": "1045.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-14",
      "measureDate": "2018-4-19",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 101,
      "userUsername": "admin_user",
      "orderDate": "2018-4-26",
      "totalAmount": "471.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-13",
      "measureDate": "2018-4-13",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 111,
      "userUsername": "admin_user",
      "orderDate": "2018-4-20",
      "totalAmount": "345.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-13",
      "measureDate": "2018-4-11",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 121,
      "userUsername": "admin_user",
      "orderDate": "2018-4-19",
      "totalAmount": "410.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-5",
      "measureDate": "2018-4-10",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 131,
      "userUsername": "admin_user",
      "orderDate": "2018-2-11",
      "totalAmount": "1142.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-7",
      "measureDate": "2018-4-18",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 141,
      "userUsername": "admin_user",
      "orderDate": "2018-2-24",
      "totalAmount": "1168.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-12",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 151,
      "userUsername": "admin_user",
      "orderDate": "2018-3-2",
      "totalAmount": "968.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-6",
      "measureDate": "2018-4-4",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 161,
      "userUsername": "admin_user",
      "orderDate": "2018-2-24",
      "totalAmount": "996.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-9",
      "measureDate": "2018-4-17",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 171,
      "userUsername": "admin_user",
      "orderDate": "2018-2-18",
      "totalAmount": "270.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-16",
      "measureDate": "2018-4-4",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 181,
      "userUsername": "admin_user",
      "orderDate": "2018-2-20",
      "totalAmount": "520.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-18",
      "measureDate": "2018-4-18",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 191,
      "userUsername": "admin_user",
      "orderDate": "2018-1-4",
      "totalAmount": "347.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-18",
      "measureDate": "2018-4-7",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 201,
      "userUsername": "admin_user",
      "orderDate": "2018-1-14",
      "totalAmount": "397.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-13",
      "measureDate": "2018-4-12",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 211,
      "userUsername": "admin_user",
      "orderDate": "2018-1-28",
      "totalAmount": "834.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-18",
      "measureDate": "2018-4-8",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 221,
      "userUsername": "admin_user",
      "orderDate": "2018-2-20",
      "totalAmount": "756.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-8",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 231,
      "userUsername": "admin_user",
      "orderDate": "2018-4-28",
      "totalAmount": "737.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-5",
      "measureDate": "2018-4-6",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 241,
      "userUsername": "admin_user",
      "orderDate": "2018-4-13",
      "totalAmount": "715.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-6",
      "measureDate": "2018-4-19",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 251,
      "userUsername": "admin_user",
      "orderDate": "2018-4-16",
      "totalAmount": "463.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-12",
      "measureDate": "2018-4-11",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 261,
      "userUsername": "admin_user",
      "orderDate": "2018-3-18",
      "totalAmount": "186.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-1",
      "measureDate": "2018-4-1",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 271,
      "userUsername": "admin_user",
      "orderDate": "2018-4-25",
      "totalAmount": "1119.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-15",
      "measureDate": "2018-4-20",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 281,
      "userUsername": "admin_user",
      "orderDate": "2018-3-19",
      "totalAmount": "810.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-7",
      "measureDate": "2018-4-18",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 291,
      "userUsername": "admin_user",
      "orderDate": "2018-3-3",
      "totalAmount": "486.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-20",
      "measureDate": "2018-4-18",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 301,
      "userUsername": "admin_user",
      "orderDate": "2018-1-17",
      "totalAmount": "1131.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-12",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 311,
      "userUsername": "admin_user",
      "orderDate": "2018-3-30",
      "totalAmount": "923.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-5",
      "measureDate": "2018-4-10",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 321,
      "userUsername": "admin_user",
      "orderDate": "2018-4-13",
      "totalAmount": "597.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-9",
      "measureDate": "2018-4-14",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 331,
      "userUsername": "admin_user",
      "orderDate": "2018-2-11",
      "totalAmount": "485.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-2",
      "measureDate": "2018-4-4",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 341,
      "userUsername": "admin_user",
      "orderDate": "2018-4-12",
      "totalAmount": "369.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-2",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 351,
      "userUsername": "admin_user",
      "orderDate": "2018-3-7",
      "totalAmount": "472.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-5",
      "measureDate": "2018-4-11",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 361,
      "userUsername": "admin_user",
      "orderDate": "2018-3-6",
      "totalAmount": "403.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-20",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 371,
      "userUsername": "admin_user",
      "orderDate": "2018-1-10",
      "totalAmount": "993.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-6",
      "measureDate": "2018-4-1",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 381,
      "userUsername": "admin_user",
      "orderDate": "2018-4-26",
      "totalAmount": "460.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-11",
      "measureDate": "2018-4-12",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 391,
      "userUsername": "admin_user",
      "orderDate": "2018-3-21",
      "totalAmount": "410.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-2",
      "measureDate": "2018-4-2",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 401,
      "userUsername": "admin_user",
      "orderDate": "2018-4-19",
      "totalAmount": "933.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-12",
      "measureDate": "2018-4-13",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 411,
      "userUsername": "admin_user",
      "orderDate": "2018-3-8",
      "totalAmount": "196.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-4",
      "measureDate": "2018-4-7",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 421,
      "userUsername": "admin_user",
      "orderDate": "2018-4-11",
      "totalAmount": "618.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-19",
      "measureDate": "2018-4-5",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 431,
      "userUsername": "admin_user",
      "orderDate": "2018-3-10",
      "totalAmount": "1032.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-2",
      "measureDate": "2018-4-9",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 441,
      "userUsername": "admin_user",
      "orderDate": "2018-2-28",
      "totalAmount": "910.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-1",
      "measureDate": "2018-4-18",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 451,
      "userUsername": "admin_user",
      "orderDate": "2018-2-5",
      "totalAmount": "932.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-19",
      "measureDate": "2018-4-8",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 461,
      "userUsername": "admin_user",
      "orderDate": "2018-4-4",
      "totalAmount": "1147.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-5",
      "measureDate": "2018-4-13",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 471,
      "userUsername": "admin_user",
      "orderDate": "2018-1-8",
      "totalAmount": "1107.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-12",
      "measureDate": "2018-4-5",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 481,
      "userUsername": "admin_user",
      "orderDate": "2018-2-29",
      "totalAmount": "383.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-4",
      "measureDate": "2018-4-12",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 491,
      "userUsername": "admin_user",
      "orderDate": "2018-4-1",
      "totalAmount": "837.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-14",
      "measureDate": "2018-4-5",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 501,
      "userUsername": "admin_user",
      "orderDate": "2018-3-15",
      "totalAmount": "981.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-14",
      "measureDate": "2018-4-20",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 511,
      "userUsername": "admin_user",
      "orderDate": "2018-4-6",
      "totalAmount": "305.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-17",
      "measureDate": "2018-4-4",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 521,
      "userUsername": "admin_user",
      "orderDate": "2018-1-27",
      "totalAmount": "727.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-10",
      "measureDate": "2018-4-12",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 531,
      "userUsername": "admin_user",
      "orderDate": "2018-2-7",
      "totalAmount": "459.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-6",
      "measureDate": "2018-4-10",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 541,
      "userUsername": "admin_user",
      "orderDate": "2018-3-29",
      "totalAmount": "351.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-5",
      "measureDate": "2018-4-17",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 551,
      "userUsername": "admin_user",
      "orderDate": "2018-2-9",
      "totalAmount": "823.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-4-3",
      "measureDate": "2018-4-3",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 561,
      "userUsername": "admin_user",
      "orderDate": "2018-2-19",
      "totalAmount": "1103.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-20",
      "measureDate": "2018-4-14",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 571,
      "userUsername": "admin_user",
      "orderDate": "2018-3-19",
      "totalAmount": "255.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-15",
      "measureDate": "2018-4-11",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 581,
      "userUsername": "admin_user",
      "orderDate": "2018-4-8",
      "totalAmount": "239.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-18",
      "measureDate": "2018-4-15",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    },
    {
      "id": 591,
      "userUsername": "admin_user",
      "orderDate": "2018-2-3",
      "totalAmount": "841.00",
      "depositeAmount": 0,
      "deliveryDate": "2018-5-2",
      "measureDate": "2018-4-6",
      "orderStatus": 3,
      "mountExist": false,
      "orderNumber": "SN521",
      "tailorOrderLineCount": 0
    }
  ]
}


var postUrl = "https://measure-notebook-api.herokuapp.com/order/update";

orders.orderLineDetailList.forEach(function (order, index) {
  // if(index>13) return;
  request({
      url: postUrl,
      auth: {
        'user': 'admin_user',
        'pass': 'admin',
        'sendImmediately': false
      },
      method: 'PUT',
      json: true,
      body:order
    },
    function (error, response) {
    if(response) console.log(response);
      if(error) return console.log(error);
    }
  )
});
