export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const RESET_CUSTOMER_FORM = 'RESET_CUSTOMER_FORM';
export const ADD_USER = 'ADDUSER';
export const ADD_ORDER = 'ADD_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
export const UPDATE_ORDER_TOTAL_AMOUNT = 'UPDATE_ORDER_TOTAL_AMOUNT';
export const ADD_ORDER_LINE ='ADD_ORDER_LINE';
export const HIDE_SIDENAV = 'HIDE_SIDENAV';
export const SET_PANEL_STATE = 'SET_PANEL_STATE';
export const SET_STEP = 'SET_STEP';
export const UPDATE_ORDER_LINE = 'UPDATE_ORDER_LINE';
export const UPDATE_ORDER_LINE_FORM = 'UPDATE_ORDER_LINE_FORM';
export const UPDATE_STEP = 'UPDATE_STEP';
export const RESET_ORDER_LINE = 'RESET_ORDER_LINE';
export const RESET_ORDER_LINES = 'RESET_ORDER_LINES';
export const ADD_ORDER_LINE_PROPERTIES = 'ADD_ORDER_LINE_PROPERTIES';
export const RESET_ORDER_LINE_PROPERTIES = 'RESET_ORDER_LINE_PROPERTIES';


